default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_manager_api_development
  username: postgres
  password: 1998
  host: localhost
  port: 5432

test:
  <<: *default
  database: task_manager_api_test

production:
  <<: *default
  database: task_manager_api_production
#   host: ec2-54-144-196-35.compute-1.amazonaws.com
#   port: 5432
#   database: ddjl1k87k150ce
#   username: wibypppqvtpvcw
#   password: ceedfc30e3b2936eda312d7b29177b3a8f2e2325ff1f41d552b9acaab300ca53
