default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_manager_api_development
  username: postgres
  password: 1998
  host: localhost
  port: 5432

test:
  <<: *default
  database: task_manager_api_test

# production:
#   <<: *default
#   database: task_manager_api_production
#   username: task_manager_api
#   password: <%= ENV['TASK_MANAGER_API_DATABASE_PASSWORD'] %>
